//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aboneliks
    {
        public int ID { get; set; }
        public int AbonelikTipId { get; set; }
        public int TarifeId { get; set; }
        public int CariId { get; set; }
        public System.DateTime AboneBasTar { get; set; }
        public System.DateTime AboneBitTar { get; set; }
        public bool AktifMi { get; set; }
    }
}
