//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbonelikArac_TB
    {
        public int ID { get; set; }
        public Nullable<int> cariId { get; set; }
        public Nullable<int> aracId { get; set; }
        public Nullable<int> abonelikId { get; set; }
        public Nullable<int> tarifeId { get; set; }
        public Nullable<System.DateTime> baslangic { get; set; }
        public Nullable<System.DateTime> bitis { get; set; }
        public Nullable<bool> AktifMi { get; set; }
        public Nullable<int> icYkmUcretsizAdet { get; set; }
        public Nullable<int> disYkmUcretsizAdet { get; set; }
        public Nullable<int> icDisYkmUcretsizAdet { get; set; }
        public Nullable<int> icYkmAdet { get; set; }
        public Nullable<int> disYkmAdet { get; set; }
        public Nullable<int> icDisYkmAdet { get; set; }
        public Nullable<decimal> toplamYkmUcret { get; set; }
        public string GirisSaat { get; set; }
        public string CikisSaat { get; set; }
        public Nullable<int> GunlukGirisDetay { get; set; }
        public Nullable<int> HaftalikGirisDetay { get; set; }
    }
}
