//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aracs
    {
        public int ID { get; set; }
        public string AracTanim { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Renk { get; set; }
        public string Plaka { get; set; }
        public string EhliyetSinifi { get; set; }
        public decimal KmUcret { get; set; }
        public int AracTipId { get; set; }
        public int CariId { get; set; }
        public int AbonelikId { get; set; }
        public int CekiciFirmaId { get; set; }
        public int YediEminGirisKayitId { get; set; }
        public string Aciklama { get; set; }
        public bool YediEminMi { get; set; }
        public bool AktifMi { get; set; }
    }
}
