//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cari_TB
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TCNo { get; set; }
        public string DogumTar { get; set; }
        public string IsTel { get; set; }
        public string EvTel { get; set; }
        public string CepTel { get; set; }
        public string IsYer { get; set; }
        public string AboneNo { get; set; }
        public string Adres { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
