//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CekiciFirmas
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string FirmaAd { get; set; }
        public string VergiDaireNo { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string CepTel { get; set; }
        public string Adres { get; set; }
        public bool AktifMi { get; set; }
    }
}
