//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CekiciHareketleri_TB
    {
        public int ID { get; set; }
        public Nullable<int> AracId { get; set; }
        public Nullable<int> SurucuId { get; set; }
        public string AracTanim { get; set; }
        public string AracAlımYeri { get; set; }
        public Nullable<System.DateTime> GetirmeZamani { get; set; }
        public Nullable<decimal> Mesafe { get; set; }
        public string Birim { get; set; }
        public Nullable<decimal> EkUcret { get; set; }
        public string UcretAciklama { get; set; }
        public Nullable<decimal> ToplamUcret { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
