//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class EhliyetBilgi_TB
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Kimlik { get; set; }
        public string VerilenIl { get; set; }
        public string VerilenIlce { get; set; }
        public string BelgeNo { get; set; }
        public Nullable<System.DateTime> VerTarih { get; set; }
        public string KulCihPro { get; set; }
        public string Sinif { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Mahalle { get; set; }
        public string Koy { get; set; }
        public Nullable<int> Cilt { get; set; }
        public string Kutuk { get; set; }
        public string Sayfa { get; set; }
        public string BabaAdi { get; set; }
        public string AnneAdi { get; set; }
        public string DogumYeri { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string KanGrubu { get; set; }
        public string Duzenleyen { get; set; }
        public Nullable<bool> VekilMi { get; set; }
        public Nullable<bool> SahipMi { get; set; }
        public Nullable<int> AracId { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
