//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class EkipPolis_TB
    {
        public int ID { get; set; }
        public Nullable<int> TrafikEkipId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Tel1 { get; set; }
        public string CepTel { get; set; }
        public string SicilNo { get; set; }
        public string TelsizKodu { get; set; }
        public string Birim { get; set; }
        public string Aciklama { get; set; }
        public Nullable<bool> AmirMi { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
