//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaturaTip_TB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FaturaTip_TB()
        {
            this.Fatura_TB = new HashSet<Fatura_TB>();
        }
    
        public int ID { get; set; }
        public string FaturaTip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fatura_TB> Fatura_TB { get; set; }
    }
}
