//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fatura_TB
    {
        public int ID { get; set; }
        public string FaturaNo { get; set; }
        public Nullable<int> FaturaTip { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<decimal> Nakit { get; set; }
        public Nullable<decimal> KKart { get; set; }
        public Nullable<decimal> Toplam { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    
        public virtual FaturaTip_TB FaturaTip_TB { get; set; }
    }
}
