//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odeme_TB
    {
        public int ID { get; set; }
        public Nullable<int> CariId { get; set; }
        public Nullable<decimal> Odenecek { get; set; }
        public Nullable<decimal> Odenen { get; set; }
        public Nullable<decimal> Kalan { get; set; }
        public Nullable<decimal> KKart { get; set; }
        public Nullable<decimal> Nakit { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
