//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruhsat1_TB
    {
        public int ID { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Plaka { get; set; }
        public string TescilSiraNo { get; set; }
        public string Marka { get; set; }
        public string TicariAd { get; set; }
        public string Cins { get; set; }
        public string MotorNo { get; set; }
        public string SaseNo { get; set; }
        public Nullable<int> NetAgirlik { get; set; }
        public Nullable<int> KatarAgirligi { get; set; }
        public Nullable<int> KoltukSayisi { get; set; }
        public Nullable<int> SilindirHacmi { get; set; }
        public string YakitCinsi { get; set; }
        public string KullanimAmaci { get; set; }
        public Nullable<System.DateTime> IlkTescilTarihi { get; set; }
        public Nullable<System.DateTime> TescilTarihi { get; set; }
        public string Tipi { get; set; }
        public string ModelYili { get; set; }
        public string AracSinifi { get; set; }
        public string Rengi { get; set; }
        public Nullable<decimal> AzamiYukluAgirlik { get; set; }
        public Nullable<decimal> RoAzamiYukluAgirlik { get; set; }
        public Nullable<int> AyaktaYolcuSayisi { get; set; }
        public Nullable<int> MotorGucu { get; set; }
        public Nullable<decimal> GucAgirlikOrt { get; set; }
        public string TipOnayNo { get; set; }
        public Nullable<int> Vekil { get; set; }
        public Nullable<int> Cari { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
