//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sirkets
    {
        public int ID { get; set; }
        public string SirketAd { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Faks { get; set; }
        public string Yetkili { get; set; }
        public string Adres { get; set; }
        public string KullaniciAd { get; set; }
        public string Parola { get; set; }
        public bool AktifMi { get; set; }
    }
}
