//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subeler_TB
    {
        public int ID { get; set; }
        public string SubeAd { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Faks { get; set; }
        public string Yetkili { get; set; }
        public string Adres { get; set; }
        public string KullaniciAd { get; set; }
        public string Parola { get; set; }
        public Nullable<int> Kapasite { get; set; }
        public Nullable<bool> AnaSubeMi { get; set; }
        public Nullable<int> SirketId { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
