//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Surucu_TB
    {
        public int ID { get; set; }
        public Nullable<int> CekiciFirmaId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Tel { get; set; }
        public string CepTel { get; set; }
        public string EhliyetSinifi { get; set; }
        public string EhliyetBelgeNo { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
