//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class YediEminCikisKayit_TB
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CikisBelgeTarihi { get; set; }
        public string CikisBelgeNo { get; set; }
        public Nullable<System.DateTime> CikisZamani { get; set; }
        public string CikisTalimatBirimi { get; set; }
        public string CikisTalimatEkibi { get; set; }
        public Nullable<int> TeslimEdenPersonel { get; set; }
        public Nullable<int> TeslimAlanVekil { get; set; }
        public Nullable<int> TeslimAlanCari { get; set; }
        public string AracCikisAciklama { get; set; }
        public string AracPlaka { get; set; }
        public string FaturaNo { get; set; }
        public Nullable<decimal> OtoparkUcret { get; set; }
        public Nullable<decimal> CekiciUcret { get; set; }
        public Nullable<decimal> ToplamUcret { get; set; }
        public Nullable<bool> AktifMi { get; set; }
    }
}
