//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class YediEminHasar_TB
    {
        public int ID { get; set; }
        public Nullable<bool> InsanMi { get; set; }
        public Nullable<bool> AracMi { get; set; }
        public Nullable<bool> OlumMu { get; set; }
        public Nullable<bool> YaralanmaMi { get; set; }
        public Nullable<bool> VekilMi { get; set; }
        public string Plaka { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Kimlik { get; set; }
        public Nullable<int> YediEminId { get; set; }
    }
}
