//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoParkProject.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class YediEminGirisKayit_TB
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Evrak { get; set; }
        public string EvrakNo { get; set; }
        public Nullable<System.DateTime> GirisZaman { get; set; }
        public Nullable<bool> KazaliMi { get; set; }
        public string KurumIbraz { get; set; }
        public string IbrazEvrakNo { get; set; }
        public string Kurum { get; set; }
        public Nullable<bool> AracliKazaMi { get; set; }
        public Nullable<bool> OlumluKazaMi { get; set; }
        public string TrafikBilgisi { get; set; }
        public string TrafikMenBilgisi { get; set; }
        public string MenAdresi { get; set; }
        public string MenZamani { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> TarifeId { get; set; }
        public Nullable<bool> FiiliHacizMi { get; set; }
        public string AracEkipman { get; set; }
        public string AracEmanet { get; set; }
        public Nullable<int> TrafikEkipId { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<int> CekiciHareketleriId { get; set; }
        public Nullable<int> CekiciId { get; set; }
    }
}
